// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc/service.proto
#ifndef GRPC_grpc_2fservice_2eproto__INCLUDED
#define GRPC_grpc_2fservice_2eproto__INCLUDED

#include "grpc/service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// The greeting service definition.
class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Send command and get a reply
    virtual ::grpc::Status Command(::grpc::ClientContext* context, const ::CommandRequest& request, ::CommandReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CommandReply>> AsyncCommand(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CommandReply>>(AsyncCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CommandReply>> PrepareAsyncCommand(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CommandReply>>(PrepareAsyncCommandRaw(context, request, cq));
    }
    // Get bytes of the specified id
    virtual ::grpc::Status GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::GetBytesReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetBytesReply>> AsyncGetBytes(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetBytesReply>>(AsyncGetBytesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetBytesReply>> PrepareAsyncGetBytes(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetBytesReply>>(PrepareAsyncGetBytesRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Send command and get a reply
      virtual void Command(::grpc::ClientContext* context, const ::CommandRequest* request, ::CommandReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Command(::grpc::ClientContext* context, const ::CommandRequest* request, ::CommandReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Command(::grpc::ClientContext* context, const ::CommandRequest* request, ::CommandReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Get bytes of the specified id
      virtual void GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CommandReply>* AsyncCommandRaw(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CommandReply>* PrepareAsyncCommandRaw(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GetBytesReply>* AsyncGetBytesRaw(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GetBytesReply>* PrepareAsyncGetBytesRaw(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Command(::grpc::ClientContext* context, const ::CommandRequest& request, ::CommandReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CommandReply>> AsyncCommand(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CommandReply>>(AsyncCommandRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CommandReply>> PrepareAsyncCommand(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CommandReply>>(PrepareAsyncCommandRaw(context, request, cq));
    }
    ::grpc::Status GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::GetBytesReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetBytesReply>> AsyncGetBytes(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetBytesReply>>(AsyncGetBytesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetBytesReply>> PrepareAsyncGetBytes(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetBytesReply>>(PrepareAsyncGetBytesRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Command(::grpc::ClientContext* context, const ::CommandRequest* request, ::CommandReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Command(::grpc::ClientContext* context, const ::CommandRequest* request, ::CommandReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Command(::grpc::ClientContext* context, const ::CommandRequest* request, ::CommandReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetBytes(::grpc::ClientContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::CommandReply>* AsyncCommandRaw(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::CommandReply>* PrepareAsyncCommandRaw(::grpc::ClientContext* context, const ::CommandRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GetBytesReply>* AsyncGetBytesRaw(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GetBytesReply>* PrepareAsyncGetBytesRaw(::grpc::ClientContext* context, const ::GetBytesRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Command_;
    const ::grpc::internal::RpcMethod rpcmethod_GetBytes_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Send command and get a reply
    virtual ::grpc::Status Command(::grpc::ServerContext* context, const ::CommandRequest* request, ::CommandReply* response);
    // Get bytes of the specified id
    virtual ::grpc::Status GetBytes(::grpc::ServerContext* context, const ::GetBytesRequest* request, ::GetBytesReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Command : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Command() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Command() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Command(::grpc::ServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommand(::grpc::ServerContext* context, ::CommandRequest* request, ::grpc::ServerAsyncResponseWriter< ::CommandReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBytes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBytes() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetBytes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBytes(::grpc::ServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBytes(::grpc::ServerContext* context, ::GetBytesRequest* request, ::grpc::ServerAsyncResponseWriter< ::GetBytesReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Command<WithAsyncMethod_GetBytes<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Command : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Command() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::CommandRequest, ::CommandReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::CommandRequest* request, ::CommandReply* response) { return this->Command(context, request, response); }));}
    void SetMessageAllocatorFor_Command(
        ::grpc::experimental::MessageAllocator< ::CommandRequest, ::CommandReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CommandRequest, ::CommandReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Command() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Command(::grpc::ServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Command(
      ::grpc::CallbackServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Command(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetBytes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetBytes() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::GetBytesRequest, ::GetBytesReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::GetBytesRequest* request, ::GetBytesReply* response) { return this->GetBytes(context, request, response); }));}
    void SetMessageAllocatorFor_GetBytes(
        ::grpc::experimental::MessageAllocator< ::GetBytesRequest, ::GetBytesReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GetBytesRequest, ::GetBytesReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetBytes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBytes(::grpc::ServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetBytes(
      ::grpc::CallbackServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetBytes(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Command<ExperimentalWithCallbackMethod_GetBytes<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Command<ExperimentalWithCallbackMethod_GetBytes<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Command : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Command() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Command() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Command(::grpc::ServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetBytes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBytes() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetBytes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBytes(::grpc::ServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Command : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Command() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Command() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Command(::grpc::ServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommand(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBytes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBytes() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetBytes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBytes(::grpc::ServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBytes(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Command : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Command() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Command(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Command() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Command(::grpc::ServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Command(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Command(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetBytes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetBytes() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBytes(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetBytes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBytes(::grpc::ServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetBytes(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetBytes(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Command : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Command() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CommandRequest, ::CommandReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CommandRequest, ::CommandReply>* streamer) {
                       return this->StreamedCommand(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Command() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Command(::grpc::ServerContext* /*context*/, const ::CommandRequest* /*request*/, ::CommandReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCommand(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CommandRequest,::CommandReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBytes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBytes() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GetBytesRequest, ::GetBytesReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GetBytesRequest, ::GetBytesReply>* streamer) {
                       return this->StreamedGetBytes(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBytes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBytes(::grpc::ServerContext* /*context*/, const ::GetBytesRequest* /*request*/, ::GetBytesReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBytes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GetBytesRequest,::GetBytesReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Command<WithStreamedUnaryMethod_GetBytes<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Command<WithStreamedUnaryMethod_GetBytes<Service > > StreamedService;
};


#endif  // GRPC_grpc_2fservice_2eproto__INCLUDED
